#!/bin/bash
set -ex
# generate configure
test -x ./configure || ./bootstrap
# configure once to set the version in build script
./configure
# build and package installer
bash ./MacOSX/build-package $@
