.PU
.ds nm \fBcardos-info\fR
.TH cardos-info 1 "December 11, 2003" "" OpenSC
.SH NAME
cardos-info \- Displays information about Card OS based security tokens
.SH SYNOPSIS
\*(nm
.RI [OPTIONS]
.SH DESCRIPTION
The \*(nm utility is used to display information about
smart cards and similar security tokens based on Siemens Card/OS M4.
.SH OPTIONS
.TP
.BR "\-\-reader " \fInumber\fP ", \-r " \fInumber\fP
Display information about the token in reader number \fInumber\fP.
The default is reader 0.
.TP
.BR "\-\-card\-driver " \fIname\fP ", \-c " \fIname\fP
Use the card driver specified by \fIname\fP.
The default is to auto-detect the correct card driver.
.TP
.BR \-\-wait ", " \-w
Causes \*(nm to wait for the token to be inserted into \fIreader\fP.
.TP
.BR \-\-verbose ", " \-v
Causes \*(nm to be more verbose. Specify this flag several times
to enable debug output in the opensc library.
.SH SEE ALSO
.BR opensc (7).
.SH AUTHORS
\*(nm was written by Juha Yrjölä and Andreas Jellinghaus <aj@dungeon.inka.de>.
This manpage was contributed by Joe Phillips <joe.phillips@innovationsw.com>
for the Debian GNU/Linux system (but may be used by others).
