dnl version.m4 - source for version.m4.ci generated by bootstrap.ci
dnl * bootstrap.ci generates version.m4.ci based on this file
dnl * if version.m4.ci exists, it is included in configure.ac
define([PACKAGE_SUFFIX], [])

