#!/bin/bash
#
# Test pkcs15-init
#
# Run this from the regression test directory.

. functions

p15_init --profile pkcs15+onepin --pin 999999 --puk 111111
p15_gen_key rsa/1024 -a 01 --key-usage sign,decrypt --pin 999999
p15_validate --pin 999999
p15_erase --secret @01=999999

