#!/bin/bash
#
# Test pkcs15-init
#
# Run this from the regression test directory.

. functions

p15_init --no-so-pin
p15_set_pin -a 01
p15_set_pin -a 02 --label "User Signature PIN"
p15_gen_key rsa/512 -a 01 --key-usage sign,decrypt
p15_gen_key rsa/512 -a 02 --key-usage nonRepudiation \
		--id feeb \
		--label "Non-Repudiation Key"
p15_validate
p15_erase --secret @01=0000 --secret @02=0000

