#include "pkcs11test_str.h"

/* Type specifications for string <-> type conversion */

static enum_specs ck_cls_s[] = {
	{ CKO_DATA             , "CKO_DATA             " },
	{ CKO_CERTIFICATE      , "CKO_CERTIFICATE      " },
	{ CKO_PUBLIC_KEY       , "CKO_PUBLIC_KEY       " },
	{ CKO_PRIVATE_KEY      , "CKO_PRIVATE_KEY      " },
	{ CKO_SECRET_KEY       , "CKO_SECRET_KEY       " },
	{ CKO_PROFILE          , "CKO_PROFILE          " },
	{ CKO_HW_FEATURE       , "CKO_HW_FEATURE       " },
	{ CKO_DOMAIN_PARAMETERS, "CKO_DOMAIN_PARAMETERS" },
	{ CKO_VENDOR_DEFINED   , "CKO_VENDOR_DEFINED   " }
};

enum_specs ck_profile_s[] = {
	{ CKP_INVALID_ID               , "CKP_INVALID_ID               " },
	{ CKP_BASELINE_PROVIDER        , "CKP_BASELINE_PROVIDER        " },
	{ CKP_EXTENDED_PROVIDER        , "CKP_EXTENDED_PROVIDER        " },
	{ CKP_AUTHENTICATION_TOKEN     , "CKP_AUTHENTICATION_TOKEN     " },
	{ CKP_PUBLIC_CERTIFICATES_TOKEN, "CKP_PUBLIC_CERTIFICATES_TOKEN" },
	{ CKP_VENDOR_DEFINED           , "CKP_VENDOR_DEFINED           " }
};

static enum_specs ck_crt_s[] = {
	{ CKC_X_509, "CKC_X_509" },
	{ CKC_X_509_ATTR_CERT, "CKC_X_509_ATTR_CERT" },
};

static enum_specs ck_key_s[] = {
	{ CKK_RSA           , "CKK_RSA            " },
	{ CKK_DSA           , "CKK_DSA            " },
	{ CKK_DH            , "CKK_DH             " },
	{ CKK_EC            , "CKK_EC             " },
	{ CKK_EC_EDWARDS    , "CKK_EC_EDWARDS     " },
	{ CKK_EC_MONTGOMERY , "CKK_EC_MONTOGMERY  " },
	{ CKK_X9_42_DH      , "CKK_X9_42_DH       " },
	{ CKK_KEA           , "CKK_KEA            " },
	{ CKK_GENERIC_SECRET, "CKK_GENERIC_SECRET " },
	{ CKK_RC2           , "CKK_RC2            " },
	{ CKK_RC4           , "CKK_RC4            " },
	{ CKK_DES           , "CKK_DES            " },
	{ CKK_DES2          , "CKK_DES2           " },
	{ CKK_DES3          , "CKK_DES3           " },
	{ CKK_CAST          , "CKK_CAST           " },
	{ CKK_CAST3         , "CKK_CAST3          " },
	{ CKK_CAST128       , "CKK_CAST128        " },
	{ CKK_RC5           , "CKK_RC5            " },
	{ CKK_IDEA          , "CKK_IDEA           " },
	{ CKK_SKIPJACK      , "CKK_SKIPJACK       " },
	{ CKK_BATON         , "CKK_BATON          " },
	{ CKK_JUNIPER       , "CKK_JUNIPER        " },
	{ CKK_CDMF          , "CKK_CDMF           " },
	{ CKK_AES           , "CKK_AES            " },
	{ CKK_BLOWFISH      , "CKK_BLOWFISH       " },
	{ CKK_TWOFISH       , "CKK_TWOFISH        " },
	{ CKK_GOSTR3410     , "CKK_GOSTR3410      " },
	{ CKK_GOSTR3411     , "CKK_GOSTR3411      " },
	{ CKK_GOST28147     , "CKK_GOST28147      " }
};

static enum_specs ck_mec_s[] = {
	{ CKM_RSA_PKCS_KEY_PAIR_GEN    , "RSA_PKCS_KEY_PAIR_GEN    " },
	{ CKM_RSA_PKCS                 , "RSA_PKCS                 " },
	{ CKM_RSA_9796                 , "RSA_9796                 " },
	{ CKM_RSA_X_509                , "RSA_X_509                " },
	{ CKM_MD2_RSA_PKCS             , "MD2_RSA_PKCS             " },
	{ CKM_MD5_RSA_PKCS             , "MD5_RSA_PKCS             " },
	{ CKM_SHA1_RSA_PKCS            , "SHA1_RSA_PKCS            " },
	{ CKM_SHA256_RSA_PKCS          , "SHA256_RSA_PKCS          " },
	{ CKM_SHA384_RSA_PKCS          , "SHA384_RSA_PKCS          " },
	{ CKM_SHA512_RSA_PKCS          , "SHA512_RSA_PKCS          " },
	{ CKM_RIPEMD128_RSA_PKCS       , "RIPEMD128_RSA_PKCS       " },
	{ CKM_RIPEMD160_RSA_PKCS       , "RIPEMD160_RSA_PKCS       " },
	{ CKM_RSA_PKCS_OAEP            , "RSA_PKCS_OAEP            " },
	{ CKM_RSA_X9_31_KEY_PAIR_GEN   , "RSA_X9_31_KEY_PAIR_GEN   " },
	{ CKM_RSA_X9_31                , "RSA_X9_31                " },
	{ CKM_SHA1_RSA_X9_31           , "SHA1_RSA_X9_31           " },
	{ CKM_RSA_PKCS_PSS             , "RSA_PKCS_PSS             " },
	{ CKM_SHA1_RSA_PKCS_PSS        , "SHA1_RSA_PKCS_PSS        " },
	{ CKM_SHA256_RSA_PKCS_PSS      , "SHA256_RSA_PKCS_PSS      " },
	{ CKM_SHA384_RSA_PKCS_PSS      , "SHA384_RSA_PKCS_PSS      " },
	{ CKM_SHA512_RSA_PKCS_PSS      , "SHA512_RSA_PKCS_PSS      " },
	{ CKM_DSA_KEY_PAIR_GEN         , "DSA_KEY_PAIR_GEN         " },
	{ CKM_DSA                      , "DSA                      " },
	{ CKM_DSA_SHA1                 , "DSA_SHA1                 " },
	{ CKM_DSA_SHA224               , "DSA_SHA224               " },
	{ CKM_DSA_SHA256               , "DSA_SHA256               " },
	{ CKM_DSA_SHA384               , "DSA_SHA384               " },
	{ CKM_DSA_SHA512               , "DSA_SHA512               " },
	{ CKM_DH_PKCS_KEY_PAIR_GEN     , "DH_PKCS_KEY_PAIR_GEN     " },
	{ CKM_DH_PKCS_DERIVE           , "DH_PKCS_DERIVE           " },
	{ CKM_X9_42_DH_KEY_PAIR_GEN    , "X9_42_DH_KEY_PAIR_GEN    " },
	{ CKM_X9_42_DH_DERIVE          , "X9_42_DH_DERIVE          " },
	{ CKM_X9_42_DH_HYBRID_DERIVE   , "X9_42_DH_HYBRID_DERIVE   " },
	{ CKM_X9_42_MQV_DERIVE         , "X9_42_MQV_DERIVE         " },
	{ CKM_RC2_KEY_GEN              , "RC2_KEY_GEN              " },
	{ CKM_RC2_ECB                  , "RC2_ECB                  " },
	{ CKM_RC2_CBC                  , "RC2_CBC                  " },
	{ CKM_RC2_MAC                  , "RC2_MAC                  " },
	{ CKM_RC2_MAC_GENERAL          , "RC2_MAC_GENERAL          " },
	{ CKM_RC2_CBC_PAD              , "RC2_CBC_PAD              " },
	{ CKM_RC4_KEY_GEN              , "RC4_KEY_GEN              " },
	{ CKM_RC4                      , "RC4                      " },
	{ CKM_DES_KEY_GEN              , "DES_KEY_GEN              " },
	{ CKM_DES_ECB                  , "DES_ECB                  " },
	{ CKM_DES_CBC                  , "DES_CBC                  " },
	{ CKM_DES_MAC                  , "DES_MAC                  " },
	{ CKM_DES_MAC_GENERAL          , "DES_MAC_GENERAL          " },
	{ CKM_DES_CBC_PAD              , "DES_CBC_PAD              " },
	{ CKM_DES2_KEY_GEN             , "DES2_KEY_GEN             " },
	{ CKM_DES3_KEY_GEN             , "DES3_KEY_GEN             " },
	{ CKM_DES3_ECB                 , "DES3_ECB                 " },
	{ CKM_DES3_CBC                 , "DES3_CBC                 " },
	{ CKM_DES3_MAC                 , "DES3_MAC                 " },
	{ CKM_DES3_MAC_GENERAL         , "DES3_MAC_GENERAL         " },
	{ CKM_DES3_CBC_PAD             , "DES3_CBC_PAD             " },
	{ CKM_DES3_CMAC                , "DES3_CMAC                " },
	{ CKM_CDMF_KEY_GEN             , "CDMF_KEY_GEN             " },
	{ CKM_CDMF_ECB                 , "CDMF_ECB                 " },
	{ CKM_CDMF_CBC                 , "CDMF_CBC                 " },
	{ CKM_CDMF_MAC                 , "CDMF_MAC                 " },
	{ CKM_CDMF_MAC_GENERAL         , "CDMF_MAC_GENERAL         " },
	{ CKM_CDMF_CBC_PAD             , "CDMF_CBC_PAD             " },
	{ CKM_MD2                      , "MD2                      " },
	{ CKM_MD2_HMAC                 , "MD2_HMAC                 " },
	{ CKM_MD2_HMAC_GENERAL         , "MD2_HMAC_GENERAL         " },
	{ CKM_MD5                      , "MD5                      " },
	{ CKM_MD5_HMAC                 , "MD5_HMAC                 " },
	{ CKM_MD5_HMAC_GENERAL         , "MD5_HMAC_GENERAL         " },
	{ CKM_SHA_1                    , "SHA_1                    " },
	{ CKM_SHA_1_HMAC               , "SHA_1_HMAC               " },
	{ CKM_SHA_1_HMAC_GENERAL       , "SHA_1_HMAC_GENERAL       " },
	{ CKM_SHA256                   , "SHA256                   " },
	{ CKM_SHA256_HMAC              , "SHA256_HMAC              " },
	{ CKM_SHA256_HMAC_GENERAL      , "SHA256_HMAC_GENERAL      " },
	{ CKM_SHA384                   , "SHA384                   " },
	{ CKM_SHA384_HMAC              , "SHA384_HMAC              " },
	{ CKM_SHA384_HMAC_GENERAL      , "SHA384_HMAC_GENERAL      " },
	{ CKM_SHA512                   , "SHA512                   " },
	{ CKM_SHA512_HMAC              , "SHA512_HMAC              " },
	{ CKM_SHA512_HMAC_GENERAL      , "SHA512_HMAC_GENERAL      " },
	{ CKM_RIPEMD128                , "RIPEMD128                " },
	{ CKM_RIPEMD128_HMAC           , "RIPEMD128_HMAC           " },
	{ CKM_RIPEMD128_HMAC_GENERAL   , "RIPEMD128_HMAC_GENERAL   " },
	{ CKM_RIPEMD160                , "RIPEMD160                " },
	{ CKM_RIPEMD160_HMAC           , "RIPEMD160_HMAC           " },
	{ CKM_RIPEMD160_HMAC_GENERAL   , "RIPEMD160_HMAC_GENERAL   " },
	{ CKM_SHA256                   , "SHA256                   " },
	{ CKM_SHA256_HMAC              , "SHA256_HMAC              " },
	{ CKM_SHA256_HMAC_GENERAL      , "SHA256_HMAC_GENERAL      " },
	{ CKM_SHA384                   , "SHA384                   " },
	{ CKM_SHA384_HMAC              , "SHA384_HMAC              " },
	{ CKM_SHA384_HMAC_GENERAL      , "SHA384_HMAC_GENERAL      " },
	{ CKM_CAST_KEY_GEN             , "CAST_KEY_GEN             " },
	{ CKM_CAST_ECB                 , "CAST_ECB                 " },
	{ CKM_CAST_CBC                 , "CAST_CBC                 " },
	{ CKM_CAST_MAC                 , "CAST_MAC                 " },
	{ CKM_CAST_MAC_GENERAL         , "CAST_MAC_GENERAL         " },
	{ CKM_CAST_CBC_PAD             , "CAST_CBC_PAD             " },
	{ CKM_CAST3_KEY_GEN            , "CAST3_KEY_GEN            " },
	{ CKM_CAST3_ECB                , "CAST3_ECB                " },
	{ CKM_CAST3_CBC                , "CAST3_CBC                " },
	{ CKM_CAST3_MAC                , "CAST3_MAC                " },
	{ CKM_CAST3_MAC_GENERAL        , "CAST3_MAC_GENERAL        " },
	{ CKM_CAST3_CBC_PAD            , "CAST3_CBC_PAD            " },
	{ CKM_CAST5_KEY_GEN            , "CAST5_KEY_GEN            " },
	{ CKM_CAST128_KEY_GEN          , "CAST128_KEY_GEN          " },
	{ CKM_CAST5_ECB                , "CAST5_ECB                " },
	{ CKM_CAST128_ECB              , "CAST128_ECB              " },
	{ CKM_CAST5_CBC                , "CAST5_CBC                " },
	{ CKM_CAST128_CBC              , "CAST128_CBC              " },
	{ CKM_CAST5_MAC                , "CAST5_MAC                " },
	{ CKM_CAST128_MAC              , "CAST128_MAC              " },
	{ CKM_CAST5_MAC_GENERAL        , "CAST5_MAC_GENERAL        " },
	{ CKM_CAST128_MAC_GENERAL      , "CAST128_MAC_GENERAL      " },
	{ CKM_CAST5_CBC_PAD            , "CAST5_CBC_PAD            " },
	{ CKM_CAST128_CBC_PAD          , "CAST128_CBC_PAD          " },
	{ CKM_RC5_KEY_GEN              , "RC5_KEY_GEN              " },
	{ CKM_RC5_ECB                  , "RC5_ECB                  " },
	{ CKM_RC5_CBC                  , "RC5_CBC                  " },
	{ CKM_RC5_MAC                  , "RC5_MAC                  " },
	{ CKM_RC5_MAC_GENERAL          , "RC5_MAC_GENERAL          " },
	{ CKM_RC5_CBC_PAD              , "RC5_CBC_PAD              " },
	{ CKM_IDEA_KEY_GEN             , "IDEA_KEY_GEN             " },
	{ CKM_IDEA_ECB                 , "IDEA_ECB                 " },
	{ CKM_IDEA_CBC                 , "IDEA_CBC                 " },
	{ CKM_IDEA_MAC                 , "IDEA_MAC                 " },
	{ CKM_IDEA_MAC_GENERAL         , "IDEA_MAC_GENERAL         " },
	{ CKM_IDEA_CBC_PAD             , "IDEA_CBC_PAD             " },
	{ CKM_GENERIC_SECRET_KEY_GEN   , "GENERIC_SECRET_KEY_GEN   " },
	{ CKM_CONCATENATE_BASE_AND_KEY , "CONCATENATE_BASE_AND_KEY " },
	{ CKM_CONCATENATE_BASE_AND_DATA, "CONCATENATE_BASE_AND_DATA" },
	{ CKM_CONCATENATE_DATA_AND_BASE, "CONCATENATE_DATA_AND_BASE" },
	{ CKM_XOR_BASE_AND_DATA        , "XOR_BASE_AND_DATA        " },
	{ CKM_EXTRACT_KEY_FROM_KEY     , "EXTRACT_KEY_FROM_KEY     " },
	{ CKM_SSL3_PRE_MASTER_KEY_GEN  , "SSL3_PRE_MASTER_KEY_GEN  " },
	{ CKM_SSL3_MASTER_KEY_DERIVE   , "SSL3_MASTER_KEY_DERIVE   " },
	{ CKM_SSL3_KEY_AND_MAC_DERIVE  , "SSL3_KEY_AND_MAC_DERIVE  " },
	{ CKM_SSL3_MASTER_KEY_DERIVE_DH, "SSL3_MASTER_KEY_DERIVE_DH" },
	{ CKM_TLS_PRE_MASTER_KEY_GEN   , "TLS_PRE_MASTER_KEY_GEN   " },
	{ CKM_TLS_MASTER_KEY_DERIVE    , "TLS_MASTER_KEY_DERIVE    " },
	{ CKM_TLS_KEY_AND_MAC_DERIVE   , "TLS_KEY_AND_MAC_DERIVE   " },
	{ CKM_TLS_MASTER_KEY_DERIVE_DH , "TLS_MASTER_KEY_DERIVE_DH " },
	{ CKM_SSL3_MD5_MAC             , "SSL3_MD5_MAC             " },
	{ CKM_SSL3_SHA1_MAC            , "SSL3_SHA1_MAC            " },
	{ CKM_MD5_KEY_DERIVATION       , "MD5_KEY_DERIVATION       " },
	{ CKM_MD2_KEY_DERIVATION       , "MD2_KEY_DERIVATION       " },
	{ CKM_SHA1_KEY_DERIVATION      , "SHA1_KEY_DERIVATION      " },
	{ CKM_PBE_MD2_DES_CBC          , "PBE_MD2_DES_CBC          " },
	{ CKM_PBE_MD5_DES_CBC          , "PBE_MD5_DES_CBC          " },
	{ CKM_PBE_MD5_CAST_CBC         , "PBE_MD5_CAST_CBC         " },
	{ CKM_PBE_MD5_CAST3_CBC        , "PBE_MD5_CAST3_CBC        " },
	{ CKM_PBE_MD5_CAST5_CBC        , "PBE_MD5_CAST5_CBC        " },
	{ CKM_PBE_MD5_CAST128_CBC      , "PBE_MD5_CAST128_CBC      " },
	{ CKM_PBE_SHA1_CAST5_CBC       , "PBE_SHA1_CAST5_CBC       " },
	{ CKM_PBE_SHA1_CAST128_CBC     , "PBE_SHA1_CAST128_CBC     " },
	{ CKM_PBE_SHA1_RC4_128         , "PBE_SHA1_RC4_128         " },
	{ CKM_PBE_SHA1_RC4_40          , "PBE_SHA1_RC4_40          " },
	{ CKM_PBE_SHA1_DES3_EDE_CBC    , "PBE_SHA1_DES3_EDE_CBC    " },
	{ CKM_PBE_SHA1_DES2_EDE_CBC    , "PBE_SHA1_DES2_EDE_CBC    " },
	{ CKM_PBE_SHA1_RC2_128_CBC     , "PBE_SHA1_RC2_128_CBC     " },
	{ CKM_PBE_SHA1_RC2_40_CBC      , "PBE_SHA1_RC2_40_CBC      " },
	{ CKM_PKCS5_PBKD2              , "PKCS5_PBKD2              " },
	{ CKM_PBA_SHA1_WITH_SHA1_HMAC  , "PBA_SHA1_WITH_SHA1_HMAC  " },
	{ CKM_KEY_WRAP_LYNKS           , "KEY_WRAP_LYNKS           " },
	{ CKM_KEY_WRAP_SET_OAEP        , "KEY_WRAP_SET_OAEP        " },
	{ CKM_SKIPJACK_KEY_GEN         , "SKIPJACK_KEY_GEN         " },
	{ CKM_SKIPJACK_ECB64           , "SKIPJACK_ECB64           " },
	{ CKM_SKIPJACK_CBC64           , "SKIPJACK_CBC64           " },
	{ CKM_SKIPJACK_OFB64           , "SKIPJACK_OFB64           " },
	{ CKM_SKIPJACK_CFB64           , "SKIPJACK_CFB64           " },
	{ CKM_SKIPJACK_CFB32           , "SKIPJACK_CFB32           " },
	{ CKM_SKIPJACK_CFB16           , "SKIPJACK_CFB16           " },
	{ CKM_SKIPJACK_CFB8            , "SKIPJACK_CFB8            " },
	{ CKM_SKIPJACK_WRAP            , "SKIPJACK_WRAP            " },
	{ CKM_SKIPJACK_PRIVATE_WRAP    , "SKIPJACK_PRIVATE_WRAP    " },
	{ CKM_SKIPJACK_RELAYX          , "SKIPJACK_RELAYX          " },
	{ CKM_KEA_KEY_PAIR_GEN         , "KEA_KEY_PAIR_GEN         " },
	{ CKM_KEA_KEY_DERIVE           , "KEA_KEY_DERIVE           " },
	{ CKM_FORTEZZA_TIMESTAMP       , "FORTEZZA_TIMESTAMP       " },
	{ CKM_BATON_KEY_GEN            , "BATON_KEY_GEN            " },
	{ CKM_BATON_ECB128             , "BATON_ECB128             " },
	{ CKM_BATON_ECB96              , "BATON_ECB96              " },
	{ CKM_BATON_CBC128             , "BATON_CBC128             " },
	{ CKM_BATON_COUNTER            , "BATON_COUNTER            " },
	{ CKM_BATON_SHUFFLE            , "BATON_SHUFFLE            " },
	{ CKM_BATON_WRAP               , "BATON_WRAP               " },
	{ CKM_EC_KEY_PAIR_GEN          , "EC_KEY_PAIR_GEN          " },
	{ CKM_ECDSA                    , "ECDSA                    " },
	{ CKM_ECDSA_SHA1               , "ECDSA_SHA1               " },
	{ CKM_ECDH1_DERIVE             , "ECDH1_DERIVE             " },
	{ CKM_ECDH1_COFACTOR_DERIVE    , "ECDH1_COFACTOR_DERIVE    " },
	{ CKM_ECMQV_DERIVE             , "ECMQV_DERIVE             " },
	{ CKM_EDDSA                    , "EDDSA                    " },
	{ CKM_XEDDSA                   , "XEDDSA                    " },
	{ CKM_JUNIPER_KEY_GEN          , "JUNIPER_KEY_GEN          " },
	{ CKM_JUNIPER_ECB128           , "JUNIPER_ECB128           " },
	{ CKM_JUNIPER_CBC128           , "JUNIPER_CBC128           " },
	{ CKM_JUNIPER_COUNTER          , "JUNIPER_COUNTER          " },
	{ CKM_JUNIPER_SHUFFLE          , "JUNIPER_SHUFFLE          " },
	{ CKM_JUNIPER_WRAP             , "JUNIPER_WRAP             " },
	{ CKM_FASTHASH                 , "FASTHASH                 " },
	{ CKM_AES_KEY_GEN              , "AES_KEY_GEN              " },
	{ CKM_AES_ECB                  , "AES_ECB                  " },
	{ CKM_AES_CBC                  , "AES_CBC                  " },
	{ CKM_AES_MAC                  , "AES_MAC                  " },
	{ CKM_AES_MAC_GENERAL          , "AES_MAC_GENERAL          " },
	{ CKM_AES_CBC_PAD              , "AES_CBC_PAD              " },
	{ CKM_AES_CTR                  , "AES_CTR                  " },
	{ CKM_AES_GCM                  , "AES_GCM                  " },
	{ CKM_AES_CCM                  , "AES_CCM                  " },
	{ CKM_AES_CMAC                 , "AES_CMAC                 " },
	{ CKM_AES_CTS                  , "AES_CTS                  " },
	{ CKM_BLOWFISH_KEY_GEN         , "BLOWFISH_KEY_GEN         " },
	{ CKM_BLOWFISH_CBC             , "BLOWFISH_CBC             " },
	{ CKM_TWOFISH_KEY_GEN          , "TWOFISH_KEY_GEN          " },
	{ CKM_TWOFISH_CBC              , "TWOFISH_CBC              " },
	{ CKM_DES_ECB_ENCRYPT_DATA     , "DES_ECB_ENCRYPT_DATA     " },
	{ CKM_DES_CBC_ENCRYPT_DATA     , "DES_CBC_ENCRYPT_DATA     " },
	{ CKM_DES3_ECB_ENCRYPT_DATA    , "DES3_ECB_ENCRYPT_DATA    " },
	{ CKM_DES3_CBC_ENCRYPT_DATA    , "DES3_CBC_ENCRYPT_DATA    " },
	{ CKM_AES_ECB_ENCRYPT_DATA     , "AES_ECB_ENCRYPT_DATA     " },
	{ CKM_AES_CBC_ENCRYPT_DATA     , "AES_CBC_ENCRYPT_DATA     " },
	{ CKM_GOSTR3410_KEY_PAIR_GEN   , "GOSTR3410_KEY_PAIR_GEN   " },
	{ CKM_GOSTR3410                , "GOSTR3410                " },
	{ CKM_GOSTR3410_WITH_GOSTR3411 , "GOSTR3410_WITH_GOSTR3411 " },
	{ CKM_GOSTR3410_KEY_WRAP       , "GOSTR3410_KEY_WRAP       " },
	{ CKM_GOSTR3410_DERIVE         , "GOSTR3410_DERIVE         " },
	{ CKM_GOSTR3411                , "GOSTR3411                " },
	{ CKM_GOSTR3411_HMAC           , "GOSTR3411_HMAC           " },
	{ CKM_GOST28147_KEY_GEN        , "GOST28147_KEY_GEN        " },
	{ CKM_GOST28147_ECB            , "GOST28147_ECB            " },
	{ CKM_GOST28147                , "GOST28147                " },
	{ CKM_GOST28147_MAC            , "GOST28147_MAC            " },
	{ CKM_GOST28147_KEY_WRAP       , "GOST28147_KEY_WRAP       " },
	{ CKM_DSA_PARAMETER_GEN        , "DSA_PARAMETER_GEN        " },
	{ CKM_DH_PKCS_PARAMETER_GEN    , "DH_PKCS_PARAMETER_GEN    " },
	{ CKM_X9_42_DH_PARAMETER_GEN   , "X9_42_DH_PARAMETER_GEN   " },
	{ CKM_AES_KEY_WRAP             , "AES_KEY_WRAP             " },
	{ CKM_VENDOR_DEFINED           , "VENDOR_DEFINED           " }
};

/* TBD */
static enum_specs ck_mgf_s[] = {
	{ CKG_MGF1_SHA1  , "CKG_MGF1_SHA1  " },
	{ CKG_MGF1_SHA224, "CKG_MGF1_SHA224" },
	{ CKG_MGF1_SHA256, "CKG_MGF1_SHA256" },
	{ CKG_MGF1_SHA384, "CKG_MGF1_SHA384" },
	{ CKG_MGF1_SHA512, "CKG_MGF1_SHA512" },
};

/* Enumerated Type Representation 
 * Each PKCS#11 type value SHALL be represented in string/text form using
 * the uppercase C macro name with the type prefix omitted.
 * E.g. CKR_OK has a representation of “OK”.
 */
static enum_specs ck_err_s[] = {
	{ CKR_OK,                               "OK" },
	{ CKR_CANCEL,                           "CANCEL" },
	{ CKR_HOST_MEMORY,                      "HOST_MEMORY" },
	{ CKR_SLOT_ID_INVALID,                  "SLOT_ID_INVALID" },
	{ CKR_GENERAL_ERROR,                    "GENERAL_ERROR" },
	{ CKR_FUNCTION_FAILED,                  "FUNCTION_FAILED" },
	{ CKR_ARGUMENTS_BAD,                    "ARGUMENTS_BAD" },
	{ CKR_NO_EVENT,                         "NO_EVENT" },
	{ CKR_NEED_TO_CREATE_THREADS,           "NEED_TO_CREATE_THREADS" },
	{ CKR_CANT_LOCK,                        "CANT_LOCK" },
	{ CKR_ATTRIBUTE_READ_ONLY,              "ATTRIBUTE_READ_ONLY" },
	{ CKR_ATTRIBUTE_SENSITIVE,              "ATTRIBUTE_SENSITIVE" },
	{ CKR_ATTRIBUTE_TYPE_INVALID,           "ATTRIBUTE_TYPE_INVALID" },
	{ CKR_ATTRIBUTE_VALUE_INVALID,          "ATTRIBUTE_VALUE_INVALID" },
	{ CKR_DATA_INVALID,                     "DATA_INVALID" },
	{ CKR_DATA_LEN_RANGE,                   "DATA_LEN_RANGE" },
	{ CKR_DEVICE_ERROR,                     "DEVICE_ERROR" },
	{ CKR_DEVICE_MEMORY,                    "DEVICE_MEMORY" },
	{ CKR_DEVICE_REMOVED,                   "DEVICE_REMOVED" },
	{ CKR_ENCRYPTED_DATA_INVALID,           "ENCRYPTED_DATA_INVALID" },
	{ CKR_ENCRYPTED_DATA_LEN_RANGE,         "ENCRYPTED_DATA_LEN_RANGE" },
	{ CKR_FUNCTION_CANCELED,                "FUNCTION_CANCELED" },
	{ CKR_FUNCTION_NOT_PARALLEL,            "FUNCTION_NOT_PARALLEL" },
	{ CKR_FUNCTION_NOT_SUPPORTED,           "FUNCTION_NOT_SUPPORTED" },
	{ CKR_KEY_HANDLE_INVALID,               "KEY_HANDLE_INVALID" },
	{ CKR_KEY_SIZE_RANGE,                   "KEY_SIZE_RANGE" },
	{ CKR_KEY_TYPE_INCONSISTENT,            "KEY_TYPE_INCONSISTENT" },
	{ CKR_KEY_NOT_NEEDED,                   "KEY_NOT_NEEDED" },
	{ CKR_KEY_CHANGED,                      "KEY_CHANGED" },
	{ CKR_KEY_NEEDED,                       "KEY_NEEDED" },
	{ CKR_KEY_INDIGESTIBLE,                 "KEY_INDIGESTIBLE" },
	{ CKR_KEY_FUNCTION_NOT_PERMITTED,       "KEY_FUNCTION_NOT_PERMITTED" },
	{ CKR_KEY_NOT_WRAPPABLE,                "KEY_NOT_WRAPPABLE" },
	{ CKR_KEY_UNEXTRACTABLE,                "KEY_UNEXTRACTABLE" },
	{ CKR_MECHANISM_INVALID,                "MECHANISM_INVALID" },
	{ CKR_MECHANISM_PARAM_INVALID,          "MECHANISM_PARAM_INVALID" },
	{ CKR_OBJECT_HANDLE_INVALID,            "OBJECT_HANDLE_INVALID" },
	{ CKR_OPERATION_ACTIVE,                 "OPERATION_ACTIVE" },
	{ CKR_OPERATION_NOT_INITIALIZED,        "OPERATION_NOT_INITIALIZED" },
	{ CKR_PIN_INCORRECT,                    "PIN_INCORRECT" },
	{ CKR_PIN_INVALID,                      "PIN_INVALID" },
	{ CKR_PIN_LEN_RANGE,                    "PIN_LEN_RANGE" },
	{ CKR_PIN_EXPIRED,                      "PIN_EXPIRED" },
	{ CKR_PIN_LOCKED,                       "PIN_LOCKED" },
	{ CKR_SESSION_CLOSED,                   "SESSION_CLOSED" },
	{ CKR_SESSION_COUNT,                    "SESSION_COUNT" },
	{ CKR_SESSION_HANDLE_INVALID,           "SESSION_HANDLE_INVALID" },
	{ CKR_SESSION_PARALLEL_NOT_SUPPORTED,   "SESSION_PARALLEL_NOT_SUPPORTED" },
	{ CKR_SESSION_READ_ONLY,                "SESSION_READ_ONLY" },
	{ CKR_SESSION_EXISTS,                   "SESSION_EXISTS" },
	{ CKR_SESSION_READ_ONLY_EXISTS,         "SESSION_READ_ONLY_EXISTS" },
	{ CKR_SESSION_READ_WRITE_SO_EXISTS,     "SESSION_READ_WRITE_SO_EXISTS" },
	{ CKR_SIGNATURE_INVALID,                "SIGNATURE_INVALID" },
	{ CKR_SIGNATURE_LEN_RANGE,              "SIGNATURE_LEN_RANGE" },
	{ CKR_TEMPLATE_INCOMPLETE,              "TEMPLATE_INCOMPLETE" },
	{ CKR_TEMPLATE_INCONSISTENT,            "TEMPLATE_INCONSISTENT" },
	{ CKR_TOKEN_NOT_PRESENT,                "TOKEN_NOT_PRESENT" },
	{ CKR_TOKEN_NOT_RECOGNIZED,             "TOKEN_NOT_RECOGNIZED" },
	{ CKR_TOKEN_WRITE_PROTECTED,            "TOKEN_WRITE_PROTECTED" },
	{ CKR_UNWRAPPING_KEY_HANDLE_INVALID,    "UNWRAPPING_KEY_HANDLE_INVALID" },
	{ CKR_UNWRAPPING_KEY_SIZE_RANGE,        "UNWRAPPING_KEY_SIZE_RANGE" },
	{ CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT, "UNWRAPPING_KEY_TYPE_INCONSISTENT" },
	{ CKR_USER_ALREADY_LOGGED_IN,           "USER_ALREADY_LOGGED_IN" },
	{ CKR_USER_NOT_LOGGED_IN,               "USER_NOT_LOGGED_IN" },
	{ CKR_USER_PIN_NOT_INITIALIZED,         "USER_PIN_NOT_INITIALIZED" },
	{ CKR_USER_TYPE_INVALID,                "USER_TYPE_INVALID" },
	{ CKR_USER_ANOTHER_ALREADY_LOGGED_IN,   "USER_ANOTHER_ALREADY_LOGGED_IN" },
	{ CKR_USER_TOO_MANY_TYPES,              "USER_TOO_MANY_TYPES" },
	{ CKR_WRAPPED_KEY_INVALID,              "WRAPPED_KEY_INVALID" },
	{ CKR_WRAPPED_KEY_LEN_RANGE,            "WRAPPED_KEY_LEN_RANGE" },
	{ CKR_WRAPPING_KEY_HANDLE_INVALID,      "WRAPPING_KEY_HANDLE_INVALID" },
	{ CKR_WRAPPING_KEY_SIZE_RANGE,          "WRAPPING_KEY_SIZE_RANGE" },
	{ CKR_WRAPPING_KEY_TYPE_INCONSISTENT,   "WRAPPING_KEY_TYPE_INCONSISTENT" },
	{ CKR_RANDOM_SEED_NOT_SUPPORTED,        "RANDOM_SEED_NOT_SUPPORTED" },
	{ CKR_RANDOM_NO_RNG,                    "RANDOM_NO_RNG" },
	{ CKR_DOMAIN_PARAMS_INVALID,            "DOMAIN_PARAMS_INVALID" },
	{ CKR_BUFFER_TOO_SMALL,                 "BUFFER_TOO_SMALL" },
	{ CKR_SAVED_STATE_INVALID,              "SAVED_STATE_INVALID" },
	{ CKR_INFORMATION_SENSITIVE,            "INFORMATION_SENSITIVE" },
	{ CKR_STATE_UNSAVEABLE,                 "STATE_UNSAVEABLE" },
	{ CKR_CRYPTOKI_NOT_INITIALIZED,         "CRYPTOKI_NOT_INITIALIZED" },
	{ CKR_CRYPTOKI_ALREADY_INITIALIZED,     "CRYPTOKI_ALREADY_INITIALIZED" },
	{ CKR_MUTEX_BAD,                        "MUTEX_BAD" },
	{ CKR_MUTEX_NOT_LOCKED,                 "MUTEX_NOT_LOCKED" },
	{ CKR_VENDOR_DEFINED,                   "VENDOR_DEFINED" }
};

/* TBD */
static enum_specs ck_usr_s[] = {
	{ CKU_SO,   "CKU_SO" },
	{ CKU_USER, "CKU_USER" },
	{ CKU_CONTEXT_SPECIFIC, "CKU_CONTEXT_SPECIFIC" }
};

static enum_specs ck_sta_s[] = {
	{ CKS_RO_PUBLIC_SESSION, "CKS_RO_PUBLIC_SESSION" },
	{ CKS_RO_USER_FUNCTIONS, "CKS_RO_USER_FUNCTIONS" },
	{ CKS_RW_PUBLIC_SESSION, "CKS_RW_PUBLIC_SESSION" },
	{ CKS_RW_USER_FUNCTIONS, "CKS_RW_USER_FUNCTIONS" },
	{ CKS_RW_SO_FUNCTIONS,   "CKS_RW_SO_FUNCTIONS" }
};

static enum_specs ck_ckd_s[] = {
	{ CKD_NULL, "CKD_NULL" },
	{ CKD_SHA1_KDF, "CKD_SHA1_KDF" },
	{ CKD_SHA224_KDF, "CKD_SHA224_KDF" },
	{ CKD_SHA256_KDF, "CKD_SHA256_KDF" },
	{ CKD_SHA384_KDF, "CKD_SHA384_KDF" },
	{ CKD_SHA512_KDF, "CKD_SHA512_KDF" },
};

static enum_specs ck_flags[] = {
	{ 0x0, "0x0" },
	/* Token info flags */
	{ CKF_RNG, "RNG" },
	{ CKF_WRITE_PROTECTED, "WRITE_PROTECTED" },
	{ CKF_LOGIN_REQUIRED, "LOGIN_REQUIRED" },
	{ CKF_USER_PIN_INITIALIZED         , "USER_PIN_INITIALIZED" },
	{ CKF_RESTORE_KEY_NOT_NEEDED, "RESTORE_KEY_NOT_NEEDED" },
	{ CKF_CLOCK_ON_TOKEN, "CLOCK_ON_TOKEN" },
	{ CKF_PROTECTED_AUTHENTICATION_PATH, "PROTECTED_AUTHENTICATION_PATH" },
	{ CKF_DUAL_CRYPTO_OPERATIONS, "DUAL_CRYPTO_OPERATIONS" },
	{ CKF_TOKEN_INITIALIZED, "TOKEN_INITIALIZED" },
	{ CKF_SECONDARY_AUTHENTICATION, "SECONDARY_AUTHENTICATION" },
	{ CKF_USER_PIN_COUNT_LOW, "USER_PIN_COUNT_LOW" },
	{ CKF_USER_PIN_FINAL_TRY, "USER_PIN_FINAL_TRY" },
	{ CKF_USER_PIN_LOCKED, "USER_PIN_LOCKED" },
	{ CKF_USER_PIN_TO_BE_CHANGED, "USER_PIN_TO_BE_CHANGED" },
	{ CKF_SO_PIN_COUNT_LOW, "SO_PIN_COUNT_LOW" },
	{ CKF_SO_PIN_FINAL_TRY, "SO_PIN_FINAL_TRY" },
	{ CKF_SO_PIN_LOCKED, "SO_PIN_LOCKED" },
	{ CKF_SO_PIN_TO_BE_CHANGED, "SO_PIN_TO_BE_CHANGED" },
	/* Session info flags */
	{ CKF_RW_SESSION, "CKF_RW_SESSION" },
	{ CKF_SERIAL_SESSION, "CKF_SERIAL_SESSION" },
	/* Slot info flags */
	{ CKF_TOKEN_PRESENT, "CKF_TOKEN_PRESENT" },
	{ CKF_REMOVABLE_DEVICE, "CKF_REMOVABLE_DEVICE" },
	{ CKF_HW_SLOT, "CKF_HW_SLOT" },
	/* Mechanism Information Flags */
	{ CKF_HW, "CKF_HW" },
	{ CKF_ENCRYPT, "CKF_ENCRYPT" },
	{ CKF_DECRYPT, "CKF_DECRYPT" },
	{ CKF_DIGEST, "CKF_DIGEST" },
	{ CKF_SIGN, "CKF_SIGN" },
	{ CKF_SIGN_RECOVER, "CKF_SIGN_RECOVER" },
	{ CKF_VERIFY, "CKF_VERIFY" },
	{ CKF_VERIFY_RECOVER, "CKF_VERIFY_RECOVER" },
	{ CKF_GENERATE, "CKF_GENERATE" },
	{ CKF_GENERATE_KEY_PAIR, "CKF_GENERATE_KEY_PAIR" },
	{ CKF_WRAP, "CKF_WRAP" },
	{ CKF_UNWRAP, "CKF_UNWRAP" },
	{ CKF_DERIVE, "CKF_DERIVE" },
	{ CKF_EXTENSION, "CKF_EXTENSION" },
};

static enum_specs ck_attribute_specs[] = {
	{ CKA_CLASS             , "CLASS" },
	{ CKA_TOKEN             , "TOKEN" },
	{ CKA_PRIVATE           , "PRIVATE"},
	{ CKA_LABEL             , "LABEL" },
	{ CKA_APPLICATION       , "APPLICATION" },
	{ CKA_VALUE             , "VALUE" },
	{ CKA_OBJECT_ID         , "OBJECT_ID" },
	{ CKA_CERTIFICATE_TYPE  , "CERTIFICATE_TYPE" },
	{ CKA_ISSUER            , "ISSUER" },
	{ CKA_SERIAL_NUMBER     , "SERIAL_NUMBER" },
	{ CKA_AC_ISSUER         , "AC_ISSUER" },
	{ CKA_OWNER             , "OWNER" },
	{ CKA_ATTR_TYPES        , "ATTR_TYPES" },
	{ CKA_TRUSTED           , "TRUSTED" },
	{ CKA_CERTIFICATE_CATEGORY, "CERTIFICATE_CATEGORY" },
	{ CKA_JAVA_MIDP_SECURITY_DOMAIN, "JAVA_MIDP_SECURITY_DOMAIN" },
	{ CKA_URL               , "URL" },
	{ CKA_HASH_OF_SUBJECT_PUBLIC_KEY, "HASH_OF_SUBJECT_PUBLIC_KEY" },
	{ CKA_HASH_OF_ISSUER_PUBLIC_KEY, "HASH_OF_ISSUER_PUBLIC_KEY" },
	{ CKA_CHECK_VALUE       , "CHECK_VALUE" },
	{ CKA_KEY_TYPE          , "KEY_TYPE" },
	{ CKA_SUBJECT           , "SUBJECT" },
	{ CKA_ID                , "ID" },
	{ CKA_SENSITIVE         , "SENSITIVE"},
	{ CKA_ENCRYPT           , "ENCRYPT"},
	{ CKA_DECRYPT           , "DECRYPT"},
	{ CKA_WRAP              , "WRAP"},
	{ CKA_UNWRAP            , "UNWRAP"},
	{ CKA_SIGN              , "SIGN"},
	{ CKA_SIGN_RECOVER      , "SIGN_RECOVER"},
	{ CKA_VERIFY            , "VERIFY"},
	{ CKA_VERIFY_RECOVER    , "VERIFY_RECOVER"},
	{ CKA_DERIVE            , "DERIVE"},
	{ CKA_START_DATE        , "START_DATE" },
	{ CKA_END_DATE          , "END_DATE" },
	{ CKA_MODULUS           , "MODULUS" },
	{ CKA_MODULUS_BITS      , "MODULUS_BITS" },
	{ CKA_PUBLIC_EXPONENT   , "PUBLIC_EXPONENT" },
	{ CKA_PRIVATE_EXPONENT  , "PRIVATE_EXPONENT" },
	{ CKA_PRIME_1           , "PRIME_1" },
	{ CKA_PRIME_2           , "PRIME_2" },
	{ CKA_EXPONENT_1        , "EXPONENT_1" },
	{ CKA_EXPONENT_2        , "EXPONENT_2" },
	{ CKA_COEFFICIENT       , "COEFFICIENT" },
	{ CKA_PUBLIC_KEY_INFO   , "PUBLIC_KEY_INFO" },
	{ CKA_PRIME             , "PRIME" },
	{ CKA_SUBPRIME          , "SUBPRIME" },
	{ CKA_BASE              , "BASE" },
	{ CKA_PRIME_BITS        , "PRIME_BITS" },
	{ CKA_SUB_PRIME_BITS    , "SUB_PRIME_BITS" },
	{ CKA_VALUE_BITS        , "VALUE_BITS" },
	{ CKA_VALUE_LEN         , "VALUE_LEN" },
	{ CKA_EXTRACTABLE       , "EXTRACTABLE" },
	{ CKA_LOCAL             , "LOCAL" },
	{ CKA_NEVER_EXTRACTABLE , "NEVER_EXTRACTABLE" },
	{ CKA_ALWAYS_SENSITIVE  , "ALWAYS_SENSITIVE" },
	{ CKA_KEY_GEN_MECHANISM , "KEY_GEN_MECHANISM" },
	{ CKA_MODIFIABLE        , "MODIFIABLE" },
	{ CKA_COPYABLE          , "COPYABLE" },
	{ CKA_EC_PARAMS         , "EC_PARAMS" },
	{ CKA_ECDSA_PARAMS      , "ECDSA_PARAMS" },
	{ CKA_EC_POINT          , "EC_POINT" },
	{ CKA_SECONDARY_AUTH    , "SECONDARY_AUTH" },
	{ CKA_AUTH_PIN_FLAGS    , "AUTH_PIN_FLAGS" },
	{ CKA_ALWAYS_AUTHENTICATE, "ALWAYS_AUTHENTICATE"},
	{ CKA_WRAP_WITH_TRUSTED , "WRAP_WITH_TRUSTED" },
	{ CKA_WRAP_TEMPLATE     , "WRAP_TEMPLATE" },
	{ CKA_UNWRAP_TEMPLATE   , "UNWRAP_TEMPLATE" },
	{ CKA_OTP_FORMAT        , "OTP_FORMAT" },
	{ CKA_OTP_LENGTH        , "OTP_LENGTH" },
	{ CKA_OTP_TIME_INTERVAL , "OTP_TIME_INTERVAL" },
	{ CKA_OTP_USER_FRIENDLY_MODE, "OTP_USER_FRIENDLY_MODE"},
	{ CKA_OTP_CHALLENGE_REQUIREMENT, "OTP_CHALLENGE_REQUIREMENT" },
	{ CKA_OTP_TIME_REQUIREMENT, "OTP_TIME_REQUIREMENT" },
	{ CKA_OTP_COUNTER_REQUIREMENT, "OTP_COUNTER_REQUIREMENT " },
	{ CKA_OTP_PIN_REQUIREMENT, "OTP_PIN_REQUIREMENT" },
	{ CKA_OTP_COUNTER       , "OTP_COUNTER" },
	{ CKA_OTP_TIME          , "OTP_TIME" },
	{ CKA_OTP_USER_IDENTIFIER, "OTP_USER_IDENTIFIER" },
	{ CKA_OTP_SERVICE_IDENTIFIER, "OTP_SERVICE_IDENTIFIER" },
	{ CKA_OTP_SERVICE_LOGO  , "OTP_SERVICE_LOGO" },
	{ CKA_OTP_SERVICE_LOGO_TYPE, "OTP_SERVICE_LOGO_TYPE" },
	{ CKA_GOSTR3410_PARAMS  , "GOSTR3410_PARAMS" },
	{ CKA_GOSTR3411_PARAMS  , "GOSTR3411_PARAMS" },
	{ CKA_GOST28147_PARAMS  , "GOST28147_PARAMS" },
	{ CKA_HW_FEATURE_TYPE   , "HW_FEATURE_TYPE" },
	{ CKA_RESET_ON_INIT     , "RESET_ON_INIT" },
	{ CKA_HAS_RESET         , "HAS_RESET" },
	{ CKA_PIXEL_X           , "PIXEL_X" },
	{ CKA_PIXEL_Y           , "PIXEL_Y" },
	{ CKA_RESOLUTION        , "RESOLUTION" },
	{ CKA_CHAR_ROWS         , "CHAR_ROWS" },
	{ CKA_CHAR_COLUMNS      , "CHAR_COLUMNS" },
	{ CKA_COLOR             , "COLOR" },
	{ CKA_BITS_PER_PIXEL    , "BITS_PER_PIXEL" },
	{ CKA_CHAR_SETS         , "CHAR_SETS" },
	{ CKA_ENCODING_METHODS  , "ENCODING_METHODS" },
	{ CKA_MIME_TYPES        , "MIME_TYPES" },
	{ CKA_MECHANISM_TYPE    , "MECHANISM_TYPE" },
	{ CKA_PROFILE_ID        , "PROFILE_ID" },
	{ CKA_REQUIRED_CMS_ATTRIBUTES, "REQUIRED_CMS_ATTRIBUTES " },
	{ CKA_DEFAULT_CMS_ATTRIBUTES, "DEFAULT_CMS_ATTRIBUTES " },
	{ CKA_SUPPORTED_CMS_ATTRIBUTES, "SUPPORTED_CMS_ATTRIBUTES " },
	{ CKA_ALLOWED_MECHANISMS, "ALLOWED_MECHANISMS " }
};

#define SZ_SPECS sizeof(enum_specs)

enum_spec ck_types[] = {
	{ OBJ_T, ck_cls_s, sizeof(ck_cls_s) / SZ_SPECS, "CK_OBJECT_CLASS"     },
	{ PROFILE_T, ck_profile_s, sizeof(ck_profile_s)/SZ_SPECS, "CK_PROFILE"},
	{ KEY_T, ck_key_s, sizeof(ck_key_s) / SZ_SPECS, "CK_KEY_TYPE"         },
	{ CRT_T, ck_crt_s, sizeof(ck_crt_s) / SZ_SPECS, "CK_CERTIFICATE_TYPE" },
	{ MEC_T, ck_mec_s, sizeof(ck_mec_s) / SZ_SPECS, "CK_MECHANISM_TYPE"   },
	{ MGF_T, ck_mgf_s, sizeof(ck_mgf_s) / SZ_SPECS, "CK_RSA_PKCS_MGF_TYPE"},
	{ USR_T, ck_usr_s, sizeof(ck_usr_s) / SZ_SPECS, "CK_USER_TYPE"        },
	{ STA_T, ck_sta_s, sizeof(ck_sta_s) / SZ_SPECS, "CK_STATE"        },
	{ CKD_T, ck_ckd_s, sizeof(ck_ckd_s) / SZ_SPECS, "CK_EC_KDF_TYPE"      },
	{ RV_T,  ck_err_s, sizeof(ck_err_s) / SZ_SPECS, "CK_RV"               },
	{ FLG_T, ck_flags, sizeof(ck_flags) / SZ_SPECS, "CK_FLAGS"},
	{ ATR_T, ck_attribute_specs, sizeof(ck_attribute_specs) / SZ_SPECS, "CK_ATTRIBUTE" },
};

/* Lookups for conversion */
static int
lookup_string_spec(enum_spec *spec, const char *value, CK_ULONG_PTR result)
{
	for (CK_ULONG i = 0; i < spec->size; i++) {
		if (strcmp(spec->specs[i].name, value) == 0) {
			*result = spec->specs[i].type;
			return PKCS11TEST_SUCCESS;
		}
	}
	return PKCS11TEST_INVALID_VALUE_NAME;
}

static int
lookup_enum_spec(enum_spec *spec, CK_ULONG value, char **result)
{
	for (CK_ULONG i = 0; i < spec->size; i++) {
		if (spec->specs[i].type == value) {
			*result = spec->specs[i].name;
			return PKCS11TEST_SUCCESS;
		}
	}
	return PKCS11TEST_INVALID_VALUE_NAME;
}

int
lookup_string(CK_ULONG type, const char *value, CK_ULONG_PTR result)
{
	for (CK_ULONG i = 0; ck_types[i].type < ( sizeof(ck_types) / sizeof(enum_spec) ) ; i++) {
		if (ck_types[i].type == type) {
			return lookup_string_spec(&(ck_types[i]), value, result);
		}
	}
	return PKCS11TEST_INVALID_VALUE_NAME;
}

int
lookup_enum(CK_ULONG type, CK_ULONG value, char **result)
{
	CK_ULONG i;

	for (i = 0; ck_types[i].type < ( sizeof(ck_types) / sizeof(enum_spec) ) ; i++) {
		if (ck_types[i].type == type) {
			return lookup_enum_spec(&(ck_types[i]), value, result);
		}
	}
	return PKCS11TEST_INVALID_VALUE_NAME;
}
