.TH sc_file_free 3 "April 2003" "OpenSC Programmer's Manual
.SH NAME
sc_file_free \- release an OpenSC file object
.SH SYNOPSIS
.nf
.B #include <opensc.h>
.sp
.BI "void sc_file_free(sc_file_t *" file ");
.fi
.SH DESCRIPTION
This function releases a file object previously allocated by
\fBsc_select_file\fP.
.SH SEE ALSO
.BR sc_file (3),
.BR sc_select_file (3).
.SH AUTHOR
This manual page was written by Olaf Kirch <okir@suse.de>
