.TH sc_release_context 3 "April 2003" "OpenSC Programmer's Manual
.SH NAME
sc_release_context \- release OpenSC context
.SH SYNOPSIS
.nf
.B #include <opensc.h>
.sp
.BI "int sc_release_context(struct sc_context **" ctx ");
.fi
.SH DESCRIPTION
This function releasees an OpenSC context previously obtain through
a call to \fBsc_establish_context\fP(3). No further calls to
OpenSC using this context are possible after this.
.PP
\fIctx\fP is the pointer to the context that should be released.
.SH SEE ALSO
.BR sc_establish_context (3).
.SH AUTHOR
This manual page was written by Olaf Kirch <okir@suse.de>
