name: Linux (meson)


on:
  push:
      branches: ['sbom']
  pull_request:
    branches: master

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  ubuntu:
    name: Native build on Ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential meson git openssl docbook-xsl xsltproc gengetopt libpcsclite-dev libssl-dev libcmocka-dev libreadline-dev
      - uses: actions/checkout@v4

      - name: Configure project
        run: meson setup -Dcomponents=pkcs11,tools,sm -Ddriver=pcsc -Dopenpace=enabled -Dopenssl=enabled -Dreadline=enabled -Dzlib=enabled -Dtests=true -Ddoc=true -Dman=true build/
      - name: Build project
        run: meson compile -C build/ -v
      - name: Run unit tests
        run: meson test -C build/ -v
      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Ubuntu_Meson_Testlog
          path: build/meson-logs/testlog.txt

      - name: Configure project (light)
        run: meson setup -Dcomponents=pkcs11,tools,sm -Ddriver=pcsc -Dopenpace=disabled -Dopenssl=disabled -Dreadline=disabled -Dzlib=disabled -Dtests=true -Ddoc=true -Dman=true build-light/
      - name: Build project (light)
        run: meson compile -C build-light/ -v
      - name: Run unit tests (light)
        run: meson test -C build-light/ -v
      - name: Upload test log (light)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Ubuntu_Meson_Testlog_light
          path: build-light/meson-logs/testlog.txt

      - name: Create distribution package
        run: meson dist -C build/ --formats xztar
      - name: Upload distribution package
        uses: actions/upload-artifact@v4
        with:
          name: opensc-dist
          path: build/meson-dist/opensc-*

  pkcs11:
    name: Build static PKCS#11 module
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential meson libpcsclite-dev libp11-kit-dev openjdk-21-jre
      - uses: actions/checkout@v4
      - name: Configure project
        run: meson setup --prefix=/usr -Dbuildtype=release -Db_lto=true -Db_ndebug=true -Dc_link_args=-Wl,-Bsymbolic -Dcomponents=pkcs11 -Dstatic_components=pkcs11 -Ddriver=pcsc -Dp11kit=enabled --wrap-mode=forcefallback -Dglib:libmount=disabled -Dglib:tests=false -Dglib:glib_debug=disabled -Dglib:glib_assert=false -Dglib:glib_checks=false -Dglib:sysprof=disabled -Dproxy-libintl:default_library=static -Dlibffi:default_library=static -Dzlib:tests=disabled build/
      - name: Build project
        run: meson compile -C build/ -v
      - name: build SBOM
        run: |
          npm install -g @cyclonedx/cdxgen
          cdxgen -t c -o sbom.json .
      - name: Upload the PKCS#11 module
        uses: actions/upload-artifact@v4
        with:
          name: opensc-pkcs11
          path: |
            build/src/pkcs11/opensc-pkcs11.so
            sbom.json
